version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  assignees:
  - fantinbibas
  ignore:
  - dependency-name: symfony/validator
    versions:
    - 4.4.19
    - 4.4.20
  - dependency-name: symfony/console
    versions:
    - 4.4.19
    - 4.4.20
  - dependency-name: symfony/dotenv
    versions:
    - 5.2.2
    - 5.2.3
  - dependency-name: symfony/flex
    versions:
    - 1.11.0
    - 1.12.1
  - dependency-name: symfony/templating
    versions:
    - 5.2.1
    - 5.2.2
    - 5.2.3
  - dependency-name: symfony/framework-bundle
    versions:
    - 4.4.19
  - dependency-name: phootwork/collection
    versions:
    - 2.1.2
