image: tmaier/docker-compose:latest

services:
  - docker:dind

before_script:
  - docker info
  - docker-compose --version

build:
  stage: build
  tags:
    - docker
  script:
    - docker-compose -f .build/docker-compose.yml build
    - docker-compose -f .build/docker-compose.yml up -d
    - docker-compose -f .build/docker-compose.yml exec -T php php bin/console doctrine:migrations:migrate -y

test:
  stage: test
  tags:
    - phpunit
  script:
    - docker-compose -f .build/docker-compose.yml exec -T php php bin/phpunit
