variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2

image:
  name: docker/compose:latest
  entrypoint: ["/bin/sh", "-c"]

services:
  - docker:dind

before_script:
  - docker info
  - docker-compose version

build:
  stage: build
  script:
    - docker-compose -f .build/docker-compose.yml build
    - docker-compose -f .build/docker-compose.yml up -d
    - docker-compose -f .build/docker-compose.yml exec -T php php bin/console doctrine:migrations:migrate -y

test:
  stage: test
  script:
    - docker-compose -f .build/docker-compose.yml exec -T php php bin/phpunit
