v1_secrets_create:
    path: /secrets
    methods:
      - POST
    controller: App\Controller\SecretController::create

v1_secrets_list:
    path: /secrets
    methods:
      - GET
    controller: App\Controller\SecretController::list

v1_secrets_get:
    path: /secrets/{id}
    methods:
      - GET
    controller: App\Controller\SecretController::getResource

v1_secrets_update:
    path: /secrets/{id}
    methods:
      - PATCH
    controller: App\Controller\SecretController::update
