version: '3.7'
services:
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASS}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASS}"
  php:
    build:
      context: ../
      dockerfile: ./.build/php/Dockerfile
    volumes:
      - "../:/var/www"
    environment:
      APP_ENV: prod
      APP_SECRET: "${APP_SECRET}"
      DATABASE_URL: "mysql://${DB_USER}:${DB_PASS}@db:3306/${DB_NAME}"
      JWT_SECRET_KEY: "%kernel.project_dir%/config/jwt/private.pem"
      JWT_PUBLIC_KEY: "%kernel.project_dir%/config/jwt/public.pem"
      JWT_PASSPHRASE: "${JWT_PASSPHRASE}"
  nginx:
    image: nginx
    ports:
      - "${PORT}:80"
    depends_on:
      - php
      - db
    volumes:
      - "../:/var/www"
      - "./nginx/conf:/etc/nginx/conf.d"
  composer:
    image: composer
      restart: 'no'
    command: install
    volumes:
      - "../:/app"
