name: Deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deploying Harpokrat to dev
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /var/docker-repositories/api-dev
            sudo git pull origin
            sudo docker-compose -f .build/docker-compose.yml -p api.dev up -d
            sudo docker exec -ti apidev_php_1 bash -c "cd ..; ./.deploy/container.sh"
